FROM civisanalytics/datascience-python:latest

RUN pip install xmltodict
RUN pip install dateparser
RUN pip install asyncio
RUN pip install aiohttp
RUN pip install ipdb
RUN pip install sqlalchemy
RUN pip install apache-airflow
