version: "3.2"

services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /Users/mrestrepo/proj_mobile_commons/mobile_commons_etl/src:/src
    container_name: mc_etl
    stdin_open: true
    env_file: env.list
    tty: true
    ports:
      - "8080:8080"
